excluded:

analyzer_rules:
  - unused_declaration
  - unused_import
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - first_where
  - identical_operands
  - let_var_whitespace
  - last_where
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - operator_usage_whitespace
  - redundant_nil_coalescing
  - vertical_parameter_alignment_on_call
  - yoda_condition
disabled_rules:
# 추가한 rules
  - identifier_name
  - orphaned_doc_comment
  - empty_xctest_method
  - redundant_type_annotation
  - number_separator
  - force_try
  - object_literal
  - file_name
  - sorted_imports
  - file_header
  - vertical_whitespace_opening_braces
  - vertical_whitespace_closing_braces

